Angelito
sixers23/sixers23.github.io pull request #1
Opened 2020-06-24 22:00 UTC by sixers23

2020-06-24 22:28 UTC, angeloraso requested changes

2020-06-24 22:28 UTC, angeloraso commented on script.js
> +  }
- Una solución un poco mas prolija sería usando una expresion ternaria
- Para este caso quedaría:
```
var diagnostic =
    r < 17 ? 'Desnutricion' :
    18 <= r && r <= 20? 'Bajo peso' :
    21 <= r && r <= 25.9? 'Normal' :
    26 <= r && r <= 30.9? 'Sobrepeso' :
    31 <= r && r <= 35.9? 'Obesidad' :
    36 <= r && r <= 40? 'Obesidad marcada'
    : 'Obesidad morbida';
```

2020-06-24 22:28 UTC, angeloraso commented on script.js
> +  }
- Una forma mas prolija de escribir un for (cuando no se necesita el indice para alguna utilidad en especial) es escribirlo de la forma:
```
for ( var dia of agenda ) {
document.getElementById("f").innerHTML = "Fecha: " + dia.fecha;
    document.getElementById("d").innerHTML =
      "Desayuno: " + dia.desayuno;
    document.getElementById("a").innerHTML =
      "Almuerzo: " + dia.almuerzo;
    document.getElementById("m").innerHTML =
      "Merienda: " + dia.merienda;
    document.getElementById("c").innerHTML = "Cena: " + dia.cena;
}
```

2020-06-24 22:28 UTC, angeloraso commented on script.js
> +}
- La funcion mostrarAgenda() pareciera que hace lo mismo que el bloque de arriba. Porque se repite?

2020-06-24 22:28 UTC, angeloraso commented on script.js
>    console.log(agenda);
- Al llevar a produccion un codigo, no es apropiado dejar los console.log. Expone la estructura interna del codigo al usuario, lo que puede significar posibles vulnerabilidades

2020-06-24 22:58 UTC, sixers23 commented on script.js
> +}
Se repite porque esta en construcción un modulo que imprima todos los elementos "dia" con esa funcion.

2020-06-24 22:58 UTC, sixers23 commented on script.js
>    console.log(agenda);
Fue quitado.

2020-06-25 20:53 UTC, sixers23 commented
Hoy los cambios fueron sobre todo de estilos Angie!

2020-06-25 20:53 UTC, merged